baseURL = "http://localhost:1313"
title = "Design Guidelines"
theme = "regionhalland"
description = ""
languageCode = "sv-se"
DefaultContentLanguage = "sv"

[Params]
  RSSLink = "/index.xml"
  author = "Region Halland" # add your company name
  email = "joel.sanden@regionhalland.se"
  github_repository = "https://github.com/RegionHalland/design.regionhalland.se"
  version = "0.0.3"
  content_path = "https://github.com/RegionHalland/design.regionhalland.se/tree/production/content"

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
      disable = false
      simple = false
    [privacy.twitter]
      disable = false
      enableDNT = false
      simple = false
    [privacy.vimeo]
      disable = false
      simple = false
    [privacy.youtube]
      disable = false
      privacyEnhanced = true
