baseURL = "http://localhost:1313"
title = "Design Guidelines"
theme = "regionhalland"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
languageCode = "sv-se"
DefaultContentLanguage = "sv"

[Params]
  RSSLink = "/index.xml"
  author = "Region Halland" # add your company name
  email = "joel.sanden@regionhalland.se"
  github_repository = "https://github.com/RegionHalland/design.regionhalland.se"
  version = "2.0.0"
