backend:
  name: git-gateway
  branch: production # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"



collections:
  - name:         "pages"
    label:        "Standardsida" # Used in the UI
    folder:       "content/" # The path to the folder where the documents are stored
    create:       true # Allow users to create new documents in this collection
    slug:         "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:       # The fields for each document, usually in front matter
      - label:    "Rubrik"
        name:     "title"
        widget:   "string"

      - label:    "Sidans namn i t.ex. menyer, brödsmulor m.m."
        required: false
        name:     "linkname"
        widget:   "string"

      - label:    "Sidbeskrivning"
        name:     "description"
        widget:   "string"

      - label:    "Publiceringsdatum"
        name:     "date"
        required: false
        widget:   "datetime"

      - label:    "Är sidan under uppbyggnad?"
        name:     "draft"
        required: false
        widget:   "boolean"
        default:  true

      - label:    "Sidinnehåll"
        name:     "body"
        widget:   "markdown"
