# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  design.regionhalland.se:
    env:
      db_password: GwdGTU3Tagux37TU#^F4GwCZeh[wxZLthmYW$Lpchh38rqPD[wj8tpUVbrcfv7t
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "32@cvas!j0eK+5j&@S{t_>CqL6myuhs7l,g`-BRh=j(B6+U,Kfai35&v5;Jv8G4j"
      secure_auth_key: "8|6x{!S-LtHZuI/>Z9oc`(o+*h^zzgt$4*3yY.z+S1wXel>[|)cz;Zb>4Qd_rqY9"
      logged_in_key: "914vZ-N@v}D67+pNv}*#yvJ7GH_L.>=%r]h<@yL/eLIx5@Mx;}u95j@b(&Lu[K_N"
      nonce_key: "7(/W3#xWk-eR`P_}1`*t+|@)ZE,Qe}$mBfPjcbHz#Lzm{s}3tu^0e?0N[u0Y^C;m"
      auth_salt: "gQ)2<e9v!6q6Jd0Y1E,jeO{yDIg1XYY31vTDURIMY]ZoD<#]nTv#o5>{J3X&rTS-"
      secure_auth_salt: "(|7|b<o?lvW6pHP:BB|.S??@<_(*[_Q}gs81Wj.w$0txkRg0BTs/Rtr_AE&j]@,q"
      logged_in_salt: ",6$(<Pp6mK?HfN{G9e6>=L?qos5box|bnZte]Rt/{c`QWC9QkewEV!G+3i:@35KG"
      nonce_salt: "A31rYcQA}6{gID]^ZpSI&I&jWP!bpZ0;tz+Z;[t(%7jlj/z5F-D/g`*]B/7Q:SfC"
